apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: my-custom-mysql:latest  # This is your custom image
          resources:
            requests:
              memory: "512Mi"   
              cpu: "250m"       
            limits:
              memory: "1Gi"     
              cpu: "1"          
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"
            - name: MYSQL_DATABASE
              value: "exampledb"
          ports:
            - containerPort: 3306
